export const experience = [
	{
		startDate: "2022",
		endDate: "Present",
		title: "Senior Frontend Engineer",
		company: "Insight Global",
		description:
			"Worked with Chick-fil-A to rebuild an employee-facing web application that controlled daily store operations. Provided technical leadership and guidance to the team.",
		technologies: [
			"React",
			"TypeScript",
			"React Query",
			"React Hook Form",
			"Jest",
			"Testing Library",
			"Cypress",
			"I18N",
		],
		url: "https://insightglobal.com",
	},
	{
		startDate: "2020",
		endDate: "2022",
		title: "Frontend Engineer",
		company: "NCR Voyix",
		description:
			"Led the implementation of major features to a digital banking web application. Helped mentor junior developers and onboard new team members.",
		technologies: [
			"React",
			"TypeScript",
			"Redux",
			"Formik",
			"Material UI",
			"Google Maps API",
			"Jest",
			"Testing Library",
			"ADA",
			"L10N",
		],
		url: "https://www.ncrvoyix.com",
	},
	{
		startDate: "2018",
		endDate: "2020",
		title: "Frontend Engineer",
		company: "Eventology (Fan Guru)",
		description:
			"Built and maintained an event service web application that complemented a mobile app which offered ticketing and augmented reality (AR) experiences.",
		technologies: [
			"React",
			"TypeScript",
			"MobX",
			"Storybook",
			"Styled Components",
			"Jest",
			"Testing Library",
			"AWS",
		],
		url: "https://www.eventology.io",
	},
	{
		startDate: "2018",
		title: "Full Stack Engineer",
		company: "DevMountain",
		description:
			"Developed three full-stack projects to demonstrate proficiency in various technologies and concepts.",
		technologies: [
			"React",
			"Node",
			"Express",
			"PostgreSQL",
			"MongoDB",
			"AWS",
			"Firebase",
		],
		url: "https://devmountain.com",
	},
];
